_core:
  default_config_hash: H6eJw1LUelLIiYueMLGVfJAVh43mkuf_F_ho2-FTybk
uuid: d40c35ac-a7cb-4444-8e61-01b271e2a382
langcode: en
status: true
id: taxonomy_term.ats_placement_status
target_entity_type_id: taxonomy_term
target_bundle: ats_placement_status
default_langcode: site_default
language_alterable: false
