_core:
  default_config_hash: Og7I4_hLCIeu9hVYMXCeKLg3uZ3JzdrM9miz6Q8mBUg
uuid: 730e4ebd-e126-4348-b20d-09e716de7c65
langcode: en
status: true
id: taxonomy_term.ats_screening_status
target_entity_type_id: taxonomy_term
target_bundle: ats_screening_status
default_langcode: site_default
language_alterable: false
